### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/jscodeshift-isort#2]
Moved from https://github.com/hi-ogawa/jscodeshift-isort/pull/1#issue-1596882231

- [ ] chore
  - rename package to `isort-ts`? probably separate repository
- [ ] deal with syntax error (probably somewhere in upstream)
  - `Error: did not recognize object of type "TSSatisfiesExpression"`
  - it seems there exist more cases https://github.com/benjamn/ast-types/issues
  - maybe we should just use babel directly as it will probably get most up-to-date/reliable syntax support
    - https://gist.github.com/donaldpipowitch/222b673fc3af4aee5a797920099b7ddd
    - https://github.com/codemod-js/codemod
  - Ideas https://github.com/hi-ogawa/jscodeshift-isort/pull/4
  - it would be ideal if we can depend on tsc's parser directly, for example via `ts-morph` (but just transpile only?)
    - probably we can (ab)use typescript transformer api directly cf. https://gist.github.com/hi-ogawa/cb338b4765d25321b120b2a47819abcc?
    - thus package would only require `typescript` as peer dependency?
- [ ] testing
  - [ ] collect test cases from somewhere
    - type import, default import, star import, import assersion
    - multiple sections
    - preserve comment and new lines?
  - [ ] doghood my projects https://github.com/hi-ogawa/web-ext-tab-manager/pull/15
- [ ] perf
  - [ ] cache
  - [ ] ts/tsx parser might be slower?
- [ ] customize order
  - https://github.com/trivago/prettier-plugin-sort-imports/blob/8d191fc9be85f20ff742456a333858f92ffdd860/src/index.ts#L9
  - https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
  - detect builtin? https://github.com/import-js/eslint-plugin-import/blob/d5fc8b670dc8e6903dbb7b0894452f60c03089f5/src/core/importType.js#L30
